
services:

  backend:
    build:
      context: ./
      target: express-dev
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ./wedding-invitation-app-express/src
          action: rebuild
          target: /usr/local/app/src
        - path: ./wedding-invitation-app-express/package.json
          action: rebuild

  client:
    build:
      context: ./
      target: react-dev
    develop:
      watch:
        - path: ./wedding-invitation-app-react/src
          action: sync
          target: /usr/local/app/src
        - path: ./wedding-invitation-app-react/package.json
          action: rebuild
    ports:
      - 3000:3000

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 80:80
      
volumes:
  todo-mysql-data:
