services:
  express:
    build:
      context: ./
      target: express-dev
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wedding
      MYSQL_USER: root
      MYSQL_HOST: mysql
      NEXT_PUBLIC_APP_PORT: 8080
      NEXT_PUBLIC_APP_HOST: http://localhost
      TOKEN: prambanan1
      DEVELOPE_MODE: true
      NODE_ENV: production
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ./express/src
          action: rebuild
          target: /usr/local/app/src
        - path: ./express/package.json
          action: rebuild

  react:
    build:
      context: ./
      target: react-dev
    develop:
      watch:
        - path: ./react/src
          action: sync
          target: /usr/local/app/src
        - path: ./react/package.json
          action: rebuild
    ports:
      - 3000:3000

  mysql:
    image: mysql:8.0
    volumes:
      - wedding-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wedding

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 80:80

volumes:
  wedding-mysql-data:
