services:
  express:
    build:
      context: ./
      target: express-prod
      dockerfile: Express.Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

  nextjs:
    build:
      context: ./
      target: react-prod
      dockerfile: React.Dockerfile
    ports:
      - 3000:3000
    container_name: nextjs
    restart: always

  mysql:
    image: mysql:8.0
    volumes:
      - wedding-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wedding
    healthcheck:
      test: "exit 0"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8888:8888
      
  nginx:
    build:
      context: ./
      target: nginx
      dockerfile: Nginx.Dockerfile
    # image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  wedding-mysql-data:
