services:
  express:
    container_name: express
    build:
      context: ./
      target: express-prod
      dockerfile: Express.Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

  nextjs:
    build:
      context: ./
      target: react-prod
      dockerfile: React.Dockerfile
    ports:
      - 3000:3000
    container_name: nextjs
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    volumes:
      - wedding-mysql-data:/wedding
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wedding
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8888:8888

  nginx:
    build:
      context: ./
      target: nginx
      dockerfile: Nginx.Dockerfile
    # image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always

volumes:
  wedding-mysql-data:
