name: Build Wedding App
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ vars.USERNAME }}
          host: ${{ vars.HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/app
            git pull origin main
            git status
            docker compose stop
            docker compose build
            docker compose up -d
