name: Build Wedding App
on:
  push:
    branches:
      - disabled
jobs:
  cd:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@v1.0.3
        if: startsWith(github.event.head_commit.message, 'run-build-workflow')
        with:
          username: ${{ vars.USERNAME }}
          host: ${{ vars.HOST }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            # installs nvm (Node Version Manager)
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
            # download and install Node.js (you may need to restart the terminal)
            nvm install 20
            # verifies the right Node.js version is in the environment
            node -v 
            # verifies the right npm version is in the environment
            npm -v 


            mkdir -p ~/app
            cd ~/app
            echo yes | git clone https://github.com/Harits19/wedding-app.git .
            git remote add origin https://github.com/Harits19/wedding-app.git
            git pull origin main
            git status

            cd react

            rm -rf .env
            touch .env
            echo "${{ secrets.ENV_REACT }}" >> .env

            if [ -d database ]; then
              echo "database folder already exist"
            else
              echo "start create local database folder"
              mkdir -p database
              cd database
              touch attendance.json greeting.json whitelist.json
              echo "[]" >> *.json
              cd ..
            fi

            npm install next
            npm run build

            npm install pm2 -g
            pm2 del all
            pm2 start npm --name nextjs -- start --
            sudo ufw allow 80
            sudo ufw reload

