name: Build Wedding App
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@v1.0.3
        if: startsWith(github.event.head_commit.message, 'run-build-workflow')
        with:
          username: ${{ vars.USERNAME }}
          host: ${{ vars.HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo chmod 666 /var/run/docker.sock
            mkdir -p ~/app
            cd ~/app
            echo yes | git clone https://github.com/Harits19/wedding-app.git .
            git remote add origin https://github.com/Harits19/wedding-app.git
            git pull origin main
            git status

            rm -rf .env
            touch .env
            echo "${{ secrets.ENV_FILE }}" >> .env
            
            rm -rf ssl.key
            touch ssl.key
            echo "${{ secrets.SSL_KEY }}" >> ssl.key

            rm -rf ssl.crt
            touch ssl.crt
            echo "${{ secrets.SSL_CRT }}" >> ssl.crt

            docker compose stop
            docker compose build
            docker compose up -d
